trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'release'

steps:
- task: DotNetCoreCLI@2
  displayName: DotNet Restore
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: 'build'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: DotNet Test
  inputs:
    command: 'test'
    configuration: '$(buildConfiguration)'
